#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 xtt
"""
第十批英文词条：关于页的「开发者模式」（连点图标 7 次解锁）与更新弹窗预览。

用 tools/merge_lang_en.py 合并进 LangEn.kt（已存在的键不覆盖）。
"""

GROUPS = [
    ("i18n 第十批：开发者模式（关于页）", {
        "开发者模式": "Developer mode",
        "调试入口：语言菜单、更新弹窗预览、强制检查更新":
            "Debug entry: language menu, update-dialog preview, forced update check",
        "调试功能，平时用不到": "Debug tools you normally never need",
        "喵～ 开发者模式已解锁": "Meow~ Developer mode unlocked",
        "喵～ 开发者模式早就在「开发者」那组里了":
            "Meow~ Developer mode is already there in the Developers group",
        "语言菜单": "Language menu",
        "语言列表里已经出现「猫娘语」：设置 → 外观与语言 → 语言":
            "\u300cCatgirl\u300d is already in the language list: Settings > Appearance & language > Language",
        "打开后语言列表里才会出现彩蛋语言「猫娘语」":
            "Only when this is on does the hidden language \u300cCatgirl\u300d appear in the language list",
        "语言菜单已打开": "Language menu on",
        "语言菜单已关闭": "Language menu off",
        "预览更新弹窗": "Preview the update dialog",
        "不管当前是什么版本，直接弹一次更新提示，用来看弹窗排版":
            "Shows the update dialog once no matter which version you are on, so you can check its layout",
        "正在检查…能连上就用真实的新版本信息，否则用示例内容":
            "Checking\u2026 real release info is used when reachable, otherwise sample text",
        "下次启动强制检查更新": "Force an update check on next launch",
        "清掉「今天已经检查过」的记录，下次打开 App 必定检查一次（模拟第一次进入）":
            "Clears today's check record, so the next launch always checks once (mimics a first run)",
        "下次打开 App 会强制检查一次更新": "The app will force one update check on next launch",
        "用真实检查结果预览：%s": "Previewing with the real check result: %s",
        "没查到新版本，用示例内容预览": "No newer release found; previewing with sample text",
        "发现新版本 %s（预览）": "New version %s available (preview)",
        "开发者模式预览：这张弹窗是造出来的，不代表真有新版本。":
            "Developer mode preview: this dialog is fabricated and does not mean a real new version exists.",
        "这些开关只影响本机，不会改变 AI 能用的工具。":
            "These switches only affect this device and never change the tools the AI can use.",
        "这是开发者模式生成的示例更新说明。\n" +
        "· 正文长度、换行、以及下面的按钮排版，都可以拿这张弹窗参考；\n" +
        "· 真检查到新版本时，这里显示的是 GitHub Release 里的说明正文；\n" +
        "· 点「去下载」会打开 Releases 页面。":
            "Sample release notes generated by developer mode.\n" +
            "\u00b7 Use this dialog as a reference for the body length, line breaks and the button layout below;\n" +
            "\u00b7 When a real new release is found, this area shows the body from the GitHub Release;\n" +
            "\u00b7 Tapping \u300cDownload\u300d opens the Releases page.",
    }),
]

STALE_KEYS = []
